### PR TITLE
Admin menu

### LINKED ISSUE #322: Create navigation Menu for Admin
Currently `/admin` (after login) is a long page of unrelated things.  We are going to move this into a menu structure with separate components.

The new `/admin` page should say "Welcome to dataskeptic.com administration portal."  

Add a menu system similar to this one: https://dcrazed.com/wp-content/uploads/2014/02/long-dropdown.jpg

The menu should have "CMS", "Orders", and "Email"

Sub-elements should be:

CMS > CMS pending
CMS > CMS recent
CMS > Feature of the week
CMS > Add Related Content
CMS > Recent Related Content
Orders > New*
Email > Send

* The "Orders" menu has only one element called "New".  It should include the two sections from existing admin labeled "Order processing" and "Recent orders".

Email > Send goes to "Send Confirmation Email"

### PR DESCRIPTION
**Pull request by glozhkovoy**
Fixes #322

### CODE REVIEW

**Comment by glozhkovoy** [comment]
How it looks

jq5yzudriv

**Comment by kylepolich** [comment]
@glozhkovoy Great progress.  I love this.

**Comment by kylepolich** [comment]
@glozhkovoy This PR is not close to being ready.  It doesn't even compile when you run `npm run dev`.  You need to do better testing before submitting PRs.  At a minimum, `npm run dev` needs to be tested.

I found the that problem was in `routes.jsx` and I fixed it.  However, other problems remain.  The send email section is now broken.  The Orders area is missing the most important part where you can enter a new order.

**Comment by glozhkovoy** [comment]
My fault. I didn't pushed merge conflicts resolving. 

Regarding the emails, currently i see the following error response:
```{"message":"Email address is not verified. The following identities failed the check in region US-EAST-1: order@dataskeptic.com","code":"MessageRejected","time":"2018-01-11T07:35:29.490Z","requestId":"ff02cb1e-f6a1-11e7-898f-0fb3775d4c83","statusCode":400,"retryable":false,"retryDelay":96.88521644900305}```

Maybe that issue is based on the AWS config?

**Comment by kylepolich** [comment]
The problems I mentioned have not been resolved.

THESE PROBLEMS WERE NOT FIXED:

The send email section is now broken.  - I tried it with correct IAM creds and its still not working.  I get an error message which is not appropriate (see below).  Please update.

The Orders area is missing the most important part where you can enter a new order.  THIS MUST BE FIXED!!!!!!!!  (See second screenshot)

screen shot 2018-01-15 at 8 40 28 pm

screen shot 2018-01-15 at 8 43 05 pm

**Comment by glozhkovoy** [comment]
Just checked - email sent is working. Maybe AWS took time to update the config.

**Comment by glozhkovoy** [comment]
Returned missed section `Order Processing`

screen shot 2018-01-16 at 10 30 20 am

**Comment by kylepolich** [comment]
@glozhkovoy Populate button is no longer working.

**Pull request merged**
