### PR TITLE
Exposed API for chat bot [Not Ready]

### LINKED ISSUE #156: Expose APIs for chat bot
We are going to be introducing a chatbot.  It will be a 100% stand alone service running on a separate EC2 instance.  The website will make it available using an iframe as described in #154 .

The bot is going to help the user pick out an episode to listen to.  Then it will ask the user "Would you like me to play that for you?"  When user types "yes", the BOT wants to make a call to let dataskeptic.com know to play this track in the current browser which contains the iframe.

Is it possible?

I want the same option to have the Bot add something to the shopping cart also.

What is the best implementation?

### PR DESCRIPTION
**Pull request by glozhkovoy**
Fixed #156

### CODE REVIEW

**Comment by kylepolich** [comment]
Due to whitespace changes made during this commit, it's very difficult to see what the change is.  Can you please minimize whitespace changes in future commits so they are easier to review?

**Comment by glozhkovoy** [comment]
Yep, sorry for auto formatting. Here is a little changes to handle outside messages (from chatbot f.e.) – https://github.com/data-skeptic/dataskeptic.com/pull/184/files#diff-07f7a5789bac6ce076ca5d2c23cd515cR168

**Comment by glozhkovoy** [comment]
Added #186 
To test use in project folder: 
```python -mSimpleHTTPServer 5000``` 

When you open chat bot modal, app sends to chatbot iframe current url. 
wqka2hwanl

**Comment by kylepolich** [comment]
This has been blocked by me for some time.  I need to get back to it.

**Pull request closed without merging**
