### PR TITLE
Audio level indicator

### LINKED ISSUE #90: Audio level indicator component
We should have a component that looks something like this:

<AudioLevelIndicator bars=5 />

image

I don't know how many bars I want, so let's make it a parameter.

The bars should be rectangles that fill the width of the component and have rounded corners.

We should be able to easily control some design choices (probably in CSS):

- Height of bar
- Height of space between bars

The bars should have the color 3A3B3B when silent.

When audio is being recorded, take the logarithm of the absolute value of the magnitude.  Divide that value by the max value, call it `x`.  Since `0 <= x <= 1`, it can be used as a percentage.  We should change the color of that percentage of bars.  The indicator color should be F0D943

Another Issue will define where this Component gets included.

### PR DESCRIPTION
**Pull request by glozhkovoy**
Fixes #90

**About the component.** 
You could specify almost all parameters like bar width or margin. 
To use it an `<audio>` html component should have unique `id` attribute. 

Live demo are stored at `/rfc/example` page.

### CODE REVIEW

**Comment by glozhkovoy** [comment]
Start work on this. 

Component is able to mount to the any audio on the page.

P.S. don't worry about the crazy graph. It's just some trance song.

u68kxnrdwp

**Comment by glozhkovoy** [comment]
I think it's closed to your vision. Any extra work (like trying to duplicate led panel pixel in pixel) could take much more times.


pavrt8sykc

**Comment by kylepolich** [comment]
@glozhkovoy I am confused by the PR.  This looks like it only works with `<audio>` but RFC is not an audio tag.  How does this deliver on #90?

**Comment by glozhkovoy** [comment]
Actually it used it to listen recorder audio – here https://github.com/data-skeptic/dataskeptic.com/blob/dev/shared/Recorder/Containers/RecorderFlowContainer/RecorderFlowContainer.js#L483.

I have updated PR to simply attach it to the proposals page.

**Comment by glozhkovoy** [comment]
As I understand it should work/look like this one. Correct?

da0nuewkge

**Comment by kylepolich** [comment]
@glozhkovoy , no the movie shown above is not right.  It is showing the EQ for the recorded message.  This is too late.  The user needs feedback WHILE they are recording to ensure their microphone is working correctly.

**Comment by glozhkovoy** [comment]
It was not specified at #90. 

I have updated following PR to show eq on recording:

bony3ai9uc

**Pull request merged**
