### PR TITLE
Env Variables

### LINKED ISSUE #490: Update config / boot of site
Right now, the site assumes that the config file is available locally as config/config.json.  We want to move more towards environment variables for configuration.  However, our configuration is fairly complication.  I want to keep it as a file, rather than pull out every small detail to an ENV var.

Thus, the site will be provided with three environment variables:

AWS_ACCESS_KEY
AWS_SECRET_KEY
AWS_CONFIG_S3_BUCKET
AWS_CONFIG_S3_KEY

The new site code should behave as follows:
1) Check if config/config.json exists.  If so, you are done!
2) If not, retrieve it from S3
3) Store the downloaded version in config/config.json for next time
4) Use the downloaded version to finish initialization

During the booting process of the site, there will be some delay as the config file is downloaded.  This is not a problem.  However, once it is available, the site should then proceed with the rest of the Promises to finish the load.

@gleblozhkovoy, I will have you work with @jing9932 on some of the details.

### PR DESCRIPTION
**Pull request by gleblozhkovoy**
Fixes #490

### CODE REVIEW

**Comment by gleblozhkovoy** [comment]
We have one configuration file called `.env.example`. **Do not put any values in it.** 

To start use "fake" environment on DEV(in other words locally) just copy `.env.example` to `.env` and fill the values.

On any new variable do not forget to put it on `.env.example` (and commit=>push).

On `dev` mode system check that you have all required variables value in `.env`.

@kylepolich make sure that all environment variables are exists on the server

**Comment by kylepolich** [comment]
@gleblozhkovoy This branch doesn't compile

**Comment by gleblozhkovoy** [comment]
Just merged with current `dev`. Is problem still exists?

**Comment by kylepolich** [comment]
@gleblozhkovoy recent commits make it worse now.
```
kpolich:dataskeptic.com kylepolich$ npm run dev

> dataskeptic.com@1.0.0 dev /Users/kylepolich/git/ds/dataskeptic.com
> NODE_ENV=dev NODE_PATH=$NODE_PATH:./shared babel-node --presets es2015,stage-2 --harmony .

module.js:544
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kylepolich/git/ds/dataskeptic.com/shared/backend/v1/proposals.js:7:1)
    at Module._compile (module.js:641:30)
    at loader (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kylepolich/git/ds/dataskeptic.com/server.jsx:17:1)
    at Module._compile (module.js:641:30)
    at loader (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/babel-register/lib/node.js:144:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dataskeptic.com@1.0.0 dev: `NODE_ENV=dev NODE_PATH=$NODE_PATH:./shared babel-node --presets es2015,stage-2 --harmony .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dataskeptic.com@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kylepolich/.npm/_logs/2018-02-27T15_57_55_301Z-debug.log
kpolich:dataskeptic.com kylepolich$ npm i 
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-m+qzzcn7KUxEmd1gMbchF+Y2eIUbieUaxkWtptyHywrX0rE8QEYqPC07Vuy4Wm32/xE16NcdBctb8S0Xe/5IeQ== integrity checksum failed when using sha512: wanted sha512-m+qzzcn7KUxEmd1gMbchF+Y2eIUbieUaxkWtptyHywrX0rE8QEYqPC07Vuy4Wm32/xE16NcdBctb8S0Xe/5IeQ== but got sha1-No8lEtefnUb9/HE0mueHi7weuVw=. (25587 bytes)
WARN registryWARN Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
 registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-kKvNJn6Mm93gAczWVJg7wH+wGYWNrDHdWvpUmHyEsgCtIwwo3bqPtV4tR5tuPaUhTOo/kvhVwd8XwwOllGYkbg== integrity checksum failed when using sha512: wanted sha512-kKvNJn6Mm93gAczWVJg7wH+wGYWNrDHdWvpUmHyEsgCtIwwo3bqPtV4tR5tuPaUhTOo/kvhVwd8XwwOllGYkbg== but got sha1-iTMSr2myEj3vcfV4iQAWce6yyFM=. (8851 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-4AH6Z5fzNNBcH+6XDMfA/BTt87skxqJlO0lAh3Dker5zThcAxG6mKz+iGu308UKoPPQ8Dcqx/4JhujzltRa+hQ== integrity checksum failed when using sha512: wanted sha512-4AH6Z5fzNNBcH+6XDMfA/BTt87skxqJlO0lAh3Dker5zThcAxG6mKz+iGu308UKoPPQ8Dcqx/4JhujzltRa+hQ== but got sha1-D8Z9fBQYJd6UKC3VNr7GubzoYKs=. (4142 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-S0nG3CLEQiY/ILxqtztTWH/3iRRdyBLw6KMDxnKMchrtbj2OFmehVh0WUCfW3DUrIgx/qFrJPICrq4Z4sTR9UQ== integrity checksum failed when using sha512: wanted sha512-S0nG3CLEQiY/ILxqtztTWH/3iRRdyBLw6KMDxnKMchrtbj2OFmehVh0WUCfW3DUrIgx/qFrJPICrq4Z4sTR9UQ== but got sha1-qjiWs+abSH8X4x7SFD1pqOMMLYo=. (7889 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

> dataskeptic.com@1.0.0 postinstall /Users/kylepolich/git/ds/dataskeptic.com
> . build/fixes.sh

sed: node_modules/core-js/modules/$.buffer.js: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dataskeptic.com@1.0.0 postinstall: `. build/fixes.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dataskeptic.com@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kylepolich/.npm/_logs/2018-02-27T15_58_25_444Z-debug.log
```

**Pull request closed without merging**
