### PR TITLE
Membership priority inbox [REVIEW]

### LINKED ISSUE #243: Membership priority inbox
Add the standard ContactUs Component to the Admin Portal.

If the user is in the Admin Portal, set a flag indicating that this is the page they are on.

When the user submits the message, *if* the flag for admin is set, then also use AWS SNS to send a text message to my phone.  Put my number in the config file which is +13127190752.  If the phone number does not exist in the config, then do not send the SMS message.

SMS message should be calculated like this:
var max_len = 160
var prefix = "[dataskeptic.com] "
var sms_msgs = prefix + message.substring(0, max_len - prefix.length)

### PR DESCRIPTION
**Pull request by glozhkovoy**
Fixes #243

### CODE REVIEW

**Comment by kylepolich** [comment]
@glozhkovoy I am not going to accept this PR.  There are 62 files changed.  This is too many.  The PR should only include changes relevant to #243.

**Comment by glozhkovoy** [comment]
@kylepolich I just made mistake with the base branch

**Comment by glozhkovoy** [comment]
Please add the config property "sns_number" [should be without the +]

**Comment by kylepolich** [comment]
@glozhkovoy There was no need to update this PR.  I removed it from the Waffle board over the weekend when I had to implement it myself to reach the deadlines.  Please check the Waffle board always before starting work.  Work on "Priorities" unless blocked.  Then move to "Ready"

**Comment by kylepolich** [comment]
Will not merge.

**Pull request closed without merging**
