### PR TITLE
Home new

### PR DESCRIPTION
**Pull request by urchindev**
fixed merge issues

### CODE REVIEW

**Comment by kylepolich** [comment]
@urchindev This PR shows good progress but still has some issues to address before I can accept it:

1. Add twitter handle (e.g. "@dataskeptic") which is taken from the API.  It links to Twitter profile. 

2. "View More" link is not correct destination

3. Player button is not working

4. "AD GOES HERE" needs to be removed

5. Earlier in your design, in "Latest Podcast" Component, "View More >" expanded the description.  This worked great!  Now it is no longer there.  Please put it back.

6. Please prevent "View More >" from having line splits.  Perhaps <nobr> works?  See problem below in which the line break causes awkward layout.

screen shot 2018-01-17 at 3 14 24 pm

**Comment by urchindev** [comment]
I am using prettyname field from the backend api for "View More" link

**Comment by kylepolich** [comment]
@urchindev That is the correct choice.  I noticed that the Titles/Headlines are properly linked, but the View More had a bug on my last review where it was linking to something like `/href` instead of the actual destination.

**Comment by urchindev** [comment]
1. Added twitter handle which is taken to link to Twitter profile from the API
2. Added the correct destination to "View More" link
3. Used EpisodePlayer for play button
4. removed "AD GOES HERE"
5. Added "expand" functionality for ViewMore in Podcast Component
6. Fixed line splits issue for "View More >"

**Pull request merged**
