### PR TITLE
Podcasts indicators 

### LINKED ISSUE #407: Add new indicators for logged in users on /podcasts
# Project

We want to promote on-site listening by giving useful features to logged in users connected to dataskeptic.com both on desktop and mobile.  The features will include:

1) Tracking of progress (remember how much of each episode the listener has listened to)
2) Memory of which episodes have been played / never played
3) Ability for user to mark an episode as played
4) Ability for user to mark an episode as a favorite
5) Ability for user to put episodes in a playlist

## Design

playlist

Here is the layout we want (images in S3 will be updated later).  Use EXACT links provided.  Designer will replace same file later.  Not that `favorited.png` and `not-favorited.png` are not shown in the design above.  These should be placed to the right of the headphones icon.

Images:

https://s3.amazonaws.com/dataskeptic.com/img/uiux/podcast-list-item/hover.png
https://s3.amazonaws.com/dataskeptic.com/img/uiux/podcast-list-item/played.png
https://s3.amazonaws.com/dataskeptic.com/img/uiux/podcast-list-item/playlist.png
https://s3.amazonaws.com/dataskeptic.com/img/uiux/podcast-list-item/unplayed.png
https://s3.amazonaws.com/dataskeptic.com/img/uiux/podcast-list-item/favorited.png
https://s3.amazonaws.com/dataskeptic.com/img/uiux/podcast-list-item/not-favorited.png

### Get user level data
Call this API when user first logs in and store data in `Cache`.  When updates are made (using API calls), you should update the server AND the local `Cache` at the same time.

GET: `/dev/user/played/list?email=kyle@dataskeptic.com?email=kyle@dataskeptic.com&limit=20&offset=0`

GET: `/api/user/playlist/list?email=kyle@dataskeptic.com`

GET: `/api/user/favorites/list?email=kyle@dataskeptic.com`

Note that `completed` will be either `0.0` or `1.0` guaranteed.  In the future, we might indicate the progress made in the episode, but for now, it is treated as binary for practical purposes but transmitted as float for future planning.

### Mark as played
Call this API when the user makes a chance or completes an episode in the web player.  It is preferred that you send the `blog_id`.  Second preference is to send the `guid`.  If all else fails, you can send the `media` which is a URL to the audio, but DO NOT send this without prior discussion with Kyle about why it is not possible to send either `blog_id` or `guid`.  Only one of these properties should be sent.  The example below incorrectly shows all three for demonstration purposes.

POST: `/api/user/played/update`
REQUEST: `{"email": "kyle@dataskeptic.com", "blog_id": 234, "guid": "not preferred", "media": "http://backup-only-if-blogid-impossible-dont-send-like-this.mp3", "played": 1.0}
RETURNS: `{"status": "ok"}`

This API needs to be called based on the user clicking the button on the Podcast page AND called when the Player reaches the end of an episode.

### Favorite
Call this API when the user clicks the favorite link.

POST: `/api/user/favorite/update`
REQUEST: `{"email": "kyle@dataskeptic.com", "blog_id": 234, "favorited": True}
RETURNS: `{"status": "ok"}`

### Add to Playlist
Call this API when the user clicks the "Add to Playlist" link.

POST: `/api/user/playlist/update`
REQUEST: `{"email": "kyle@dataskeptic.com", "blog_id": 234, "add": True}
RETURNS: `{"status": "ok"}`

## Implementation

Changes need to be made in `/shared/Podcasts` and in `/shared/Player`.  If any changes are needed in the rest of the project, talk to Kyle BEFORE starting any of that work.

### Playlist option

Add a new menu item in the "Membership" menu (which is a dropdown if and only if the user is logged in).  The new menu item is called "Playlist".

If user has no playlist, provide the message "You don't have anything in your playlist.  Please click one of the buttons below"  First button says "Add all episodes" which puts every podcast episode into the playlist.  Second button says "Add all episodes for 20XX" which XX is the current year.  Third button says "Visit podcast page"

If the user has playlist items, display them in order with play buttons.

## Future work (Not in this ticket)

Add to playlist from Player

Create an explainer video showing the interface

### PR DESCRIPTION
**Pull request by gleblozhkovoy**
Fixes #407

### CODE REVIEW

**Comment by glozhkovoy** [comment]
New Episode design 

3jj3gzofpn

**Comment by glozhkovoy** [comment]
Playlist page (mocked episodes)

ymheeels4k

**Comment by glozhkovoy** [comment]
Empty playlist state:

screen shot 2018-02-01 at 9 34 47 pm

**Comment by kylepolich** [comment]
@glozhkovoy Nice progress!

**Comment by kylepolich** [comment]
As mentioned in Slack, there was a bug in the API.  It said success, even if the user does not exist.  @gleblozhkovoy , please try again.  You will need to make a user account to test.  Everything should be fine now, but new code needs to be tested.

**Comment by gleblozhkovoy** [comment]
@kylepolich Ready for tests

**Comment by kylepolich** [comment]
@gleblozhkovoy Found some bugs.

If I go to /profile/playlist and click "Add all episodes" or "Add all episodes from 2018", it does not do anything.  Console outputs `undefined` from `UserPlaylist.js`

**Comment by gleblozhkovoy** [comment]
@kylepolich Do you use registered account or signed in via gmail?

**Comment by gleblozhkovoy** [comment]
This PR will fix the issue #473

**Comment by kylepolich** [comment]
@gleblozhkovoy Found two bugs.

http://g.recordit.co/r080RMpjWO.gif

To repeat:

1. Start from a blank playlist
2. Add two episodes
3. Go to Playlist page
4. Click "X" to delete the second item.  It does not go away.  I believe it is removed in the background (deleted from database), but the front end mistakenly still shows it
5. Click "X" to delete the first item, and both disappear together.

Another bug:

1. Start from a blank playlist
2. Click "Add all episodes for 2018"
3. Nothing changes for the user.  The records DO APPEAR in the database (good!), but the front end has an empty playlist.

I think there are more underlying issues than this, but these two are easy to reproduce.

**Comment by gleblozhkovoy** [comment]
Notes for myself: backend response built with `limit`. So when you delete "all" episodes it's not truly "all"

**Comment by kylepolich** [comment]
@gleblozhkovoy Latest changes break the podcast page

screen shot 2018-02-20 at 7 15 25 am

**Comment by kylepolich** [comment]
@gleblozhkovoy I tested this morning and got this error:

```
CMS_INJECT_HOMEPAGE_CONTENT
6f7d91e359c7fc9aac5b198770ad219a
[ 'eps', 202 ]
TypeError: Cannot read property 'push' of undefined
    at /Users/kylepolich/git/ds/dataskeptic.com/backend/api/v1/user.js:148:30
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by kylepolich** [comment]
@gleblozhkovoy Not working.

I pull and run the latest.  I then click on "Podcasts" and find this in the console: `[ 'eps', 0 ]`

screen shot 2018-02-26 at 7 45 39 am

Hard refresh also does not resolve it.

**Pull request merged**
