### PR TITLE
RFC fixes [Not Ready]

### LINKED ISSUE #178: RFC page is broken again
On dev branch.  See image below:

http://g.recordit.co/L0cBfV6qpg.gif

- The user can see a quick glimpse of the private information
- No ability to login
- Incorrectly saying the RFC is closed
- Should not display RFC closed message if not logged in

### PR DESCRIPTION
**Pull request by glozhkovoy**
Fixed #178

### CODE REVIEW

**Comment by kylepolich** [comment]
@glozhkovoy This did not fix things.  Please test before submitting PR!  I noticed an error in `recordingServer.js`.  It is still pointing to the old "config.json" and needs to be "config/config.json", so I can tell no testing was done because it would not have worked.  Even after I fixed this issue, it's still not working.

**Comment by glozhkovoy** [comment]
Added markdown support.

screen shot 2017-08-15 at 11 55 01

Require `npm i` before test.

Fixes #180

**Comment by glozhkovoy** [comment]
Add log out and  pre-fill the email and userName form input. http://recordit.co/sePsGpdSe1

**Comment by glozhkovoy** [comment]
Fixed #183 
Recordings / Images / Text proposals are working again

**Comment by glozhkovoy** [comment]
I checked entire flow. 

Here is an record – http://recordit.co/OUz0XhCG5r

**Pull request merged**
