### PR TITLE
Multi contributors

### LINKED ISSUE #534: Contributors on Blog Page
Currently, each blog has a single `author`.  It is a string which can be looked up in the `contributors` dictionary.

We are going to move away from this format.  However, the move will be backwards compatible.

The new functionality will allow for multiple contributors to be associated with each blog post.  The existing API has already been updated in DEV to support this.  See example:

https://xxx.execute-api.us-east-1.amazonaws.com/dev/blog/list?blog_id=326

There you will find `contributors` list.  It will be empty for most Blogs.  If this is present, then the Blog page should NOT use the `author` from the `blog`.  Ignore it, and instead use `contributors` to give a list.

Notice that the new objects have more information.  Now, the Contributor has a `contribution` field which describes what they did.  For example, "writer" and "editor" could be labels.  This label needs to be incorporated into the bio.

### PR DESCRIPTION
**Pull request by gleblozhkovoy**
Fixes #534 

screen shot 2018-03-05 at 7 23 44 pm
screen shot 2018-03-05 at 7 24 28 pm

### CODE REVIEW

**Comment by kylepolich** [comment]
@gleblozhkovoy - Great start on this!

Let's do a few updates:

Instead of "Author:", use the new dictionary value called `contribution`.  In the case of `blog_id=326`, Kyle is the "Host" and Kristine is the "Co-producer"

In the top section with "Author", "twitter", "linkedin", let's change it completely! 

Instead, let's make it similar to the BlogList:

screen shot 2018-03-05 at 8 11 32 pm

In fact, let's use the same exact Component, but make the following changes:
* Take away "by FNAME LNAME" entirely.
* Make the picture the circle version.
* For 2+ collaborators, stack them like this:

screen shot 2018-03-05 at 8 14 15 pm

**Comment by kylepolich** [comment]
In the case of the homepage:

screen shot 2018-03-05 at 8 22 37 pm

Let's do a different style / Component here.  I like the way it looks right now.  Let's put `contribution` value below the name like:

Kristine de Leon
Co-producer

Title should be smaller size and maybe italics

If there is a second Contributor, Put the second one to the right, third starts a new row.

**Comment by gleblozhkovoy** [comment]
I have played with top authors list. I was not sure with `list` flow. In case of episode we already have a list of guests and it can confuse members why here is two separated lists.

After all I took the idea from `BlogList`. And I think it's look nice and intuitive.

Regular blog
screen shot 2018-03-06 at 2 05 30 pm

Episode
screen shot 2018-03-06 at 2 05 53 pm

**Comment by gleblozhkovoy** [comment]
Updated a little bottom author box to looks like box on home to follow same design . 
Links block looks same as on contributor page. 

screen shot 2018-03-06 at 3 17 08 pm

screen shot 2018-03-06 at 3 17 19 pm

**Comment by gleblozhkovoy** [comment]
@kylepolich why `/blog/contributors/list` endpoint doesn't contain the `contribution` field?

**Comment by gleblozhkovoy** [comment]
How it will looks on home page [values hardcoded]

screen shot 2018-03-06 at 3 59 10 pm

(mobile)

screen shot 2018-03-06 at 3 59 51 pm

**Comment by kylepolich** [comment]
@gleblozhkovoy , when I try to run this branch, I get this error:
```
CMS_INJECT_HOMEPAGE_CONTENT
çHTML generation error
ReferenceError: contributor is not defined
    at /Users/kylepolich/git/ds/dataskeptic.com/shared/Home/Content/Blog/index.js:51:38
    at Array.map (<anonymous>)
    at new BlogBox (/Users/kylepolich/git/ds/dataskeptic.com/shared/Home/Content/Blog/index.js:44:17)
    at ReactCompositeComponentWrapper.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactCompositeComponent.js:148:18)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.mountChildren (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent._createContentMarkup (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactDOMComponent.js:591:32)
    at ReactDOMComponent.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactDOMComponent.js:479:29)
    at Object.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactCompositeComponentWrapper.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactCompositeComponent.js:225:34)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactCompositeComponentWrapper.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactCompositeComponent.js:225:34)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.mountComponent (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/react/lib/ReactReconciler.js:37:35)
(node:59069) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): The first argument must be one of type string or Buffer
```

The code needs to be backwards compatible and support the existing way of doing it.  Looks like the backwards compatibility is not working.

**Comment by gleblozhkovoy** [comment]
In fact, name convention is broken. We use `author` and `contributor` for the same things. Sometimes it's confusing. Missed to rename variable according the changes

**Pull request merged**
