### PR TITLE
Job Card

### LINKED ISSUE #474: Job listings
We are going to do a small test where we show job listings on the site.  We don't yet know if we are serious about this feature, but we are going to try it.

You can see one mocked example with this endpoint:

https://4sevcujref.execute-api.us-east-1.amazonaws.com/dev/cms/homepage/geo

Please add a component to the sidebar of the homepage which shows a nice Component of this job ad. 

It should include Title, location, Type, Company, and company logo.

It should also give a hyperlink to the `url` value, but we want to put a redirect in the middle so we can track the clicks.  Can we capture onClick and write an event to the console?  I can take it from there.

The description is very long.  Please make it have "View More" which works like the Podcast Description for the latest episode on the homepage.

### PR DESCRIPTION
**Pull request by gleblozhkovoy**
Fixes #474 

screen shot 2018-02-19 at 2 23 00 pm

**Notes:** Lets' avoid using plain html in in `description` field. There is no way easily cut text for view more link correctly. However we can use `<br/>` instead of `<p>`. 

In other words `description` shouldn't contain the inner tags.

### CODE REVIEW

**Comment by kylepolich** [comment]
Looking good.  One problem:

1) When I click "View More" nothing happens

Other changes:

1) Remove link to Company at top (Reaktor).  Only link will be "Apply now"

2) Remove "JOBS" title to reduce space

3) Put JOB below "LATEST PODCAST" with a little padding so the grey box is separate from the grey box of the "LATEST PODCAST".

**Comment by gleblozhkovoy** [comment]
> When I click "View More" nothing happens

We couldn't use html tags in `description`: when you'll cut it browser couldn't parse the result – html is invalid (tags not closed, e.t.c). We could use two different variables for short/long description or use a plain text.

It works for episode because episode description is plain text.

**Comment by gleblozhkovoy** [comment]
screen shot 2018-02-21 at 2 00 55 pm

**Comment by kylepolich** [comment]
@gleblozhkovoy Thanks for clarifying.  Unfortunately, they are sending it to us this way.  I will see if I can strip tags on the backend.

**Comment by kylepolich** [comment]
This is almost there.  I did some work this morning on the new Jobs feature for the homepage.  I pushed it to `job_listing` branch.  I made some nice improvements.  @gleblozhkovoy , please review what I did from this commit:

https://github.com/data-skeptic/dataskeptic.com/commit/7d98ab9050b491d4d60e622e9b49db05d04defa2

If you see any issues, please let me know.  

There is one more step that I need you to take.  The API is now expecting the `location` (city name for now) to be passed as a parameter.  I was not sure how I could get the ipinfo from the cache.  Can you wire this up and send the city name to this component, so that when it calls the API, it can provide it?

I would also like to be able to easily fake the system.  If I visit:

https://dataskeptic.com?location=chicago

Then, regardless of ipinfo, it should send "chicago" as the `location` parameter.  Good for testing!  You can find responses in "cupertino", "boston", "chicago", and others.

Kyle

**Comment by gleblozhkovoy** [comment]
@kylepolich Oh, no! Seems like you did not committed `jobs_util`

**Comment by gleblozhkovoy** [comment]
Improved endpoint to accept `location` query param

**Comment by kylepolich** [comment]
@gleblozhkovoy , sorry, added it now.

**Comment by kylepolich** [comment]
Latest pull combined with missing file on my end makes this look really good.  Ready to merge.

**Pull request merged**
