### PR TITLE
Admin link at account dropdown 

### LINKED ISSUE #416: /admin in My Account
If the user is logged in with an @dataskeptic.com address, add a new item in the "My Account" menu. called "Admin" which goes to /admin

### PR DESCRIPTION
**Pull request by glozhkovoy**
Fixes #416 

screen shot 2018-01-29 at 11 41 30 am

### CODE REVIEW

**Comment by kylepolich** [comment]
@glozhkovoy I am getting this exception, please resolve:

```
loading
TypeError: req.session.destroy is not a function
    at /Users/kylepolich/git/ds/dataskeptic.com/backend/api/v1/auth.js:236:25
    at Layer.handle [as handle_request] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:317:13)
    at /Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/kylepolich/git/ds/dataskeptic.com/node_modules/express/lib/router/index.js:174:3)
```

**Comment by kylepolich** [comment]
@glozhkovoy What's the ETA on a fix?

**Comment by glozhkovoy** [comment]
I found a reason:
when server goes down session is erase.

**Comment by glozhkovoy** [comment]
Fixed

**Pull request merged**
